export const ADD_BALANCE = "ADD_BALANCE";
export const EDIT_BALANCE = "EDIT_BALANCE";
export const LOAD_BALANCES = "LOAD_BALANCES";
export const LOAD_BALANCES_SUCESS = "LOAD_BALANCES_SUCESS";
export const ACTIVE_BALANCE = "ACTIVE_BALANCE";
export const ACTIVE_BALANCE_WIDGET = "ACTIVE_BALANCE_WIDGET";
